### ISSUE TITLE
Running locally and viewing docs

### ISSUE THREAD

**Issue by pgoldrbx** [akiran/react-foundation-apps#1]
I'm really interested in this port you're working on to build react components using foundation. The `react-bootstrap` project seems to be doing really well but there's definitely need for the equivalent for foundation.

I cloned the repo locally, ran `npm install` and `bower install`, and then ran `gulp server`. When I attempt to load `localhost:8000` in the browser, I get the rendered markup and some script tags but no application renders. Is the current version not building and stable? I'm mostly interested in seeing the generated docs, but I can read through the code to implement this as well.

Anyway, I got a couple of errors during the server task which might be related:

```
ERROR in ./lib/popup-toggle.jsx
Module not found: Error: Cannot resolve module 'tether/tether' in /react-foundation-apps/lib
 @ ./lib/popup-toggle.jsx 7:13-37

ERROR in ./docs/accordion/index.jsx
Module not found: Error: Cannot resolve module 'escape' in /react-foundation-apps/docs/accordion
 @ ./docs/accordion/index.jsx 7:17-48

ERROR in ./docs/accordion/index.jsx
Module not found: Error: Cannot resolve module 'escape' in /react-foundation-apps/docs/accordion
 @ ./docs/accordion/index.jsx 8:16-46
```

**Comment by sicknesz** [comment]
Greeting akiran, first id like to say really nice job, this was exactly what i was lookin for since last week

dev environment
- node v4.2.1 (npm v2.14.7)
- react 0.14

`Errors : Uncaught Error: Cannot find module "react-foundation-apps/lib/accordion"`
When executing this line : 
`var Accordion = require('react-foundation-apps/lib/accordion');`

When running the dev script : 
`Module not found: Error: Cannot resolve module 'react-foundation-apps/lib/accordion' in 'folder'`

After reading some of the source code i tried building it using webpack, then importing like this 
`var v = require('react-foundation-apps').Accordion; // or just require the file with requesting the Accordion object/function`
It resulted in the same as above i guess : 
`Module not found: Error: Cannot resolve 'file' or 'directory' ./lib/accordion in /vagrant/webapp/node_modules/react-foundation-apps`
I have one for each item in the framework 
- action-sheet
- iconic
- interchange
- modal, and so on. 

Any help or fix to make the accordion example works ? should i downgrade ? 

Thanks in advance.

**Comment by AbeHandler** [comment]
+1 having the same trouble. installed via npm. (^0.6.1)

**Comment by sicknesz** [comment]
updating both npm and node helped me fix the issue.
